### PR TITLE
Feature/orm - introduce the basics of an ORM to do away with custom queries where possible

### PR DESCRIPTION
**Pull request by danielhunt**
This is only a step in the ORM direction, but it should help with dev in the future.
Partially addresses #5 ... with a bit of refactoring required in the future when things start to get a little more unwieldy

It's worth noting that this actually requires a little bit of SQL schema changes. It's not normal to use the MySQL `TIME` column type, and it's not supported by `gorm` unfortunately.
This could be a blocker for you, but I've also got some handy sql migration commands for you if you want to use this PR approach \o/

**Backup your database before running this SQL, just incase**
```
-- modify the time columns on vists to be a datetime
ALTER TABLE visits MODIFY COLUMN entry_time DATETIME DEFAULT NULL;
ALTER TABLE visits MODIFY COLUMN exit_time DATETIME DEFAULT NULL;

UPDATE visits SET entry_time=CONCAT(date, concat(' ', RIGHT(entry_time, 8)));
UPDATE visits SET exit_time=CONCAT(date, concat(' ', RIGHT(exit_time, 8))) WHERE exit_time IS NOT NULL;

-- modify the time column on transactions to be a datetime too
ALTER TABLE transactions MODIFY COLUMN time_ordered DATETIME DEFAULT NULL

UPDATE transactions t INNER JOIN visits V on t.invoice_id=v.invoice_id SET t.time_ordered=CONCAT(v.date, CONCAT(' ', RIGHT(t.time_ordered, 8)));
```

### CODE REVIEW

**Comment by zramsay** [comment]
hmmm, this is also nice work, although i'm not super keen on switching from a db package from the standard library to an external package. While it is definitely much cleaner, preserving the raw sql queries is important for educational value (i.e., this repo is not only for learning go ;) The intention for #5 is really to put the raw queries in one location to slighty simplify things. Also, without #1, I'd be weary of making a change like this

**Comment by zramsay** [comment]
so, i'm going to close for now because this is not yet the direction we want to go in. Definitely in the future once the codebase has matured and stable, we can look to incorporating orm

**Comment by danielhunt** [comment]
:+1: understood - thanks for the detailed reason too

**Comment by zramsay** [comment]
oi, actually, let's keep the last three commits (can't reopen b/c your branch is deleted). these are legit bugfixes that i missed :)

**Comment by danielhunt** [comment]
Create the issues and I'll PR against them :D

**Comment by danielhunt** [comment]
I just double checked - the 3 commits that you mention here are actually to fix bugs introduced as part of my orm work. They aren't bugs in `master`, so it's safe to ignore this work entirely.

**Comment by zramsay** [comment]
ah, touche :+1:

**Pull request closed without merging**
